name: Lint

on:
  push:
    branches: ["**"]
    paths:
      - "**/*.py"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and dev deps
        run: |
          python -m pip install --upgrade pip uv
          uv sync --dev --python 3.13
          # Ensure Ruff is present even if not in pyproject
          uv pip install ruff

      - name: Ruff lint (GitHub annotations)
        run: |
          uv run ruff check . --output-format=github

      - name: Ruff format (check only)
        if: ${{ always() }}
        run: |
          uv run ruff format --check .
